config/routes.rb
Rails.application.routes.draw do
  get 'sliders/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to:  'inquiries#index'
  devise_for :users
  resources :inquiries, only:[:index ,:create,:new]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/inquiry_type.rb
class InquiryType < ApplicationRecord
end

app/models/slider.rb
class Slider < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
		@galleries = Gallery.all
	end

  def new
   	 @gallery = Gallery.new 
   end

   def create
	    params[:gallery][:image].each do |image|
	   	Gallery.create!(:image => image)
	   end
	   redirect_to galleries_path

   end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]


  def index
    @inquiries = Inquiry.all
    @galleries = Gallery.all
     @inquiry = Inquiry.new
  end
 
  def new 
    @inquiry = Inquiry.new
  end

  def create

    @inquiry = Inquiry.new(inquiry_params)
    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to root_path, notice: 'Sucessfully submitted your Inquiries and soon you wil get in touch by amdin' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  private
   
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :phone_number, :inquiry_type, :description)
    end
end

app/controllers/inquiry_types_controller.rb
class InquiryTypesController < ApplicationController
  before_action :set_inquiry_type, only: [:show, :edit, :update, :destroy]

  # GET /inquiry_types
  # GET /inquiry_types.json
  def index
    @inquiry_types = InquiryType.all
  end

  # GET /inquiry_types/1
  # GET /inquiry_types/1.json
  def show
  end

  # GET /inquiry_types/new
  def new
    @inquiry_type = InquiryType.new
  end

  # GET /inquiry_types/1/edit
  def edit
  end

  # POST /inquiry_types
  # POST /inquiry_types.json
  def create
    @inquiry_type = InquiryType.new(inquiry_type_params)

    respond_to do |format|
      if @inquiry_type.save
        format.html { redirect_to @inquiry_type, notice: 'Inquiry type was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry_type }
      else
        format.html { render :new }
        format.json { render json: @inquiry_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiry_types/1
  # PATCH/PUT /inquiry_types/1.json
  def update
    respond_to do |format|
      if @inquiry_type.update(inquiry_type_params)
        format.html { redirect_to @inquiry_type, notice: 'Inquiry type was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry_type }
      else
        format.html { render :edit }
        format.json { render json: @inquiry_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiry_types/1
  # DELETE /inquiry_types/1.json
  def destroy
    @inquiry_type.destroy
    respond_to do |format|
      format.html { redirect_to inquiry_types_url, notice: 'Inquiry type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry_type
      @inquiry_type = InquiryType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_type_params
      params.require(:inquiry_type).permit(:name)
    end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController

  def create
      params[:slider][:image].each do |image|
     	Slider.create!(:image => image)
     end
     
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/inquiry_types_helper.rb
module InquiryTypesHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/views/galleries/_index.html.erb
<div class="gallery" id="gallery">
   <div class="container">
   <h3 class="tittle">Our <span>Projects</span></h3>
     <div class="gallery-grids">
     <section>
       <ul id="da-thumbs" class="da-thumbs">
         
    			<%@galleries.each do |image| %>
    			<%unless image.image.url.blank?%>
    			  <li>
    			      <%= link_to image_tag image.image.url(:thumb), alt: image.image.url(:thumb) %>
    			  </li>
    			<% end %> 
    			<% end %>
		 
      </ul>
      </section>
    </div>
  </div>
</div>			

app/views/galleries/index.html.erb
<div class="index">
  <%= render "index" %>
</div>

app/views/galleries/new.html.erb
<%= form_for(@gallery) do |f|  %>
  <div class="fallback">
    <%= f.file_field :image ,:multiple => true%><br>
    <%= f.submit "Upload your image" %>
  </div>
<% end %>

app/views/inquiries/_form.html.erb
<div class="contact-w3-agileits" id="contact">
<div class="container">
  <h3 class="tittle"><span>contact</span></h3>

  <%= form_with(model: inquiry, local: true) do |form| %>
 
    <%= form.text_field :name,   :required => true,placeholder: "Name*" %>
  
    <%= form.email_field :email, placeholder: "Email*",:required => true %>

    <%= form.text_field :phone_number,placeholder: "Phone Number*",:required => true %>
  
    <%= form.select(:inquiry_type ,InquiryType.all.collect{|inq_type| [inq_type.name,inq_type.id]},:prompt => 'Select Inquiry_Type')%>

    <%= form.text_area :description, id: :inquiry_description ,placeholder: "Description",:required => true%>


    <%= form.submit 'submit'%>
 
 <% end %>
</div>
</div>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<div class="offer-w3layouts" id="about">
  <div class="container">
    <div class="offer-header-agile">
      <h3 class="tittle">what we <span>offer</span></h3>
      <p>we offer our customers the best services & solutions, this is our main services list</p>
    </div>
      <div class="row">
        <div class="col-md-4 offer-grid ">
          <div class="icon">
            <i class="fa fa-star-o" aria-hidden="true"></i>
          </div>
          <h4>Lorem ipsum</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus sit amet magna vehicula eleifend in in urna.</p>
          <div class="readmore-w3"><a class="readmore" href="#" data-toggle="modal" data-target="#myModal2">Read More</a></div>
            <!-- Modal2 -->
            <div class="modal fade" id="myModal2" role="dialog">
              <div class="modal-dialog">
              <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4>Aenean sagittis</h4>
                    <h5>Lorem Ipsum</h5>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>
                  </div>
                </div>
              </div>
            </div>
            <!-- //Modal2 -->
        </div>
      <div class="col-md-4 offer-grid ">
          <div class="icon">
            <i class="fa fa-map-o" aria-hidden="true"></i>
          </div>
          <h4>Lorem ipsum</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus sit amet magna vehicula eleifend in in urna.</p>
          <div class="readmore-w3"><a class="readmore" href="#" data-toggle="modal" data-target="#myModal2">Read More</a></div>
        </div>
        <div class="col-md-4 offer-grid ">
          <div class="icon">
            <i class="fa fa-university" aria-hidden="true"></i>
          </div>
          <h4>Lorem ipsum</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus sit amet magna vehicula eleifend in in urna.</p>
          <div class="readmore-w3"><a class="readmore" href="#" data-toggle="modal" data-target="#myModal2">Read More</a></div>
        </div>
        <div class="clearfix"></div>
      </div>
  </div>
</div>
<!--services-->
<div class="services-agileits" id="service">
  <div class="services-info">
    <div class="col-md-7 services-left">
    </div>
    <div class="col-md-5 services-right-agileinfo">
      <div class="right-header-w3ls">
        <h3 class="tittle">our  <span>services</span></h3>
        <p> Proin tincidunt imperdiet massa non aliquet. Nullam vestibulum sem vitae ante aliquam, eget aliquet sapien vehicula.</p>
      </div>
      <div class="service-grids-wthree">
        <div class="grid">
          <div class="service-icon">
            <i class="fa fa-home" aria-hidden="true"></i>
          </div>
          <h4>Lorem ipsum</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus sit amet magna vehicula eleifend in in urna.</p>
        </div>
        <div class="grid">
          <div class="service-icon">
            <i class="fa fa-key" aria-hidden="true"></i>
          </div>
          <h4>Lorem ipsum</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus sit amet magna vehicula eleifend in in urna.</p>
        </div>
        <div class="grid">
          <div class="service-icon">
            <i class="fa fa-building-o" aria-hidden="true"></i>
          </div>
          <h4>Lorem ipsum</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut metus sit amet magna vehicula eleifend in in urna.</p>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<!--//services-->


<!--/gallery-->
<%=render'galleries/index'%>
<!--//gallery-->

<%=render'inquiries/form', inquiry: @inquiry %>

app/views/inquiries/new.html.erb
<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/plan.html.erb
<!--pricing-tables-->
<div class="prices-w3ls" id="price">
  <div class="container">
  <h3 class="tittle two">Our <span>Plans</span></h3>
    <div class="col-md-3 price-grid">
      <div class="price-head-w3">
        <h4>Basic plan</h4>
      </div>
      <div class="price-circle-w3l">
        <h3>Adipisci velit</h3>
        <h6>9%</h6>
        <p>dolorem ipsum</p>
        <span>$ 2000</span>
      </div>
      <div class="price-info-w3ls">
        <h5>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet"</h5>
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Lorem Ipsum is simply dummy text </p>
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>It is a long est a page when looking at its layout. </p>
      </div>
    </div>
    <div class="col-md-3 price-grid mid">
      <div class="price-head-w3">
        <h4>Medium plan</h4>
      </div>
      <div class="price-circle-w3l">
        <h3>Adipisci velit</h3>
        <h6>7%</h6>
        <p>dolorem ipsum</p>
        <span>$ 2500</span>
      </div>
      <div class="price-info-w3ls table-two">
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Lorem Ipsum is simply dummy text </p>
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p>
      </div>
    </div>
    <div class="col-md-3 price-grid">
      <div class="price-head-w3">
        <h4>Premium plan</h4>
      </div>
      <div class="price-circle-w3l">
        <h3>Adipisci velit</h3>
        <h6>5%</h6>
        <p>dolorem ipsum</p>
        <span>$ 5000</span>
      </div>
      <div class="price-info-w3ls table-two">
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Lorem Ipsum is simply dummy text </p>
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
        <p><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </p>
      </div>
    </div>
  </div>
</div>
<!--//pricing-tables-->

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inquiry.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @inquiry.phone_number %>
</p>

<p>
  <strong>Inquiry type:</strong>
  <%= @inquiry.inquiry_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inquiry.description %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/team.html.erb
<!--/team-->
  <div class="team" id="team">
    <div class="container"> 
      <h3 class="tittle">Our <span>Agents</span></h3>
      <div class="main">
    <div class="col-md-3 team-sec wow fadeInLeft animated animated" data-wow-delay=".5s">
        <div class="view fifth-effect">
           <a href="#" title="Full Image"><img src="<%=asset_path('banner1.jpg') %>" alt="image" /></a>
           <div class="mask"></div>
            
        </div>  
         <div class="clearfix"></div>
        <div class="team-grid">
                 <h4>Joe</h4>
                 <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy. </p>
                    <ul class="top-icons team-icon">
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                    </ul>
              </div>  
          </div>  
        <div class="col-md-3 team-sec wow fadeInUp animated animated" data-wow-delay=".5s">
          <div class="view fifth-effect">
             <a href="#" title="Full Image"><img src="<%=asset_path('banner1.jpg') %>" alt="image" /></a>
             <div class="mask"></div>
             
          </div> 
           <div class="clearfix"></div>
            <div class="team-grid">
                 <h4>Adam</h4>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy. </p>
                    <ul class="top-icons team-icon">
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                    </ul>
              </div>          
        </div>          
                
         <div class="col-md-3 team-sec wow fadeInUp animated animated" data-wow-delay=".5s">
          <div class="view fifth-effect">
             <a href="#" title="Full Image"><img src="<%=asset_path('banner1.jpg') %>" alt="image" /></a>
             <div class="mask"></div>
          </div> 
           <div class="clearfix"></div>
          <div class="team-grid">
                 <h4>John</h4>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy. </p>
                  <ul class="top-icons team-icon">
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                    </ul>
              </div>          
        </div>        
         <div class="col-md-3 team-sec wow fadeInRight animated animated" data-wow-delay=".5s">
          <div class="view fifth-effect">
             <a href="#" title="Full Image"><img src="<%=asset_path('banner1.jpg') %>" alt="image" /></a>
             <div class="mask"></div>
          </div> 
           <div class="clearfix"></div>
            <div class="team-grid">
                 <h4>Jack</h4>
                 <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy. </p>
                    <ul class="top-icons team-icon">
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                    </ul>
              </div>          
        
         </div>
         <div class="clearfix"></div>
      </div>
     </div>
  </div>

app/views/inquiry_types/_form.html.erb
<%= form_with(model: inquiry_type, local: true) do |form| %>
  <% if inquiry_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inquiry_type.errors.count, "error") %> prohibited this inquiry_type from being saved:</h2>

      <ul>
      <% inquiry_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :inquiry_type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inquiry_types/edit.html.erb
<h1>Editing Inquiry Type</h1>

<%= render 'form', inquiry_type: @inquiry_type %>

<%= link_to 'Show', @inquiry_type %> |
<%= link_to 'Back', inquiry_types_path %>

app/views/inquiry_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inquiry Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiry_types.each do |inquiry_type| %>
      <tr>
        <td><%= inquiry_type.name %></td>
        <td><%= link_to 'Show', inquiry_type %></td>
        <td><%= link_to 'Edit', edit_inquiry_type_path(inquiry_type) %></td>
        <td><%= link_to 'Destroy', inquiry_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry Type', new_inquiry_type_path %>

app/views/inquiry_types/new.html.erb
<h1>New Inquiry Type</h1>

<%= render 'form', inquiry_type: @inquiry_type %>

<%= link_to 'Back', inquiry_types_path %>

app/views/inquiry_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inquiry_type.name %>
</p>

<%= link_to 'Edit', edit_inquiry_type_path(@inquiry_type) %> |
<%= link_to 'Back', inquiry_types_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
		<div class="footer-head-agile">
			<ul>
				<li class="contact-agile"><span class="fa-icon-w3"><i class="fa fa-phone" aria-hidden="true"></i></span>CALL NOW : 040 123456 789</li>
				<li class="logo-w3ls"><h2><a  href="index.html">Thundergc</a></h2></li>
				<li class="mail"><span class="fa-icon-w3"><i class="fa fa-envelope" aria-hidden="true"></i></span>MAIL : <a href="mailto:info@example.com">INFO@EXAMPLE.COM</a></li>
			</ul>
		</div>
		<label></label>
	<div class="container">
		<div class="footer-content-agile">
			<div class="col-md-4 about-us-agile">
				<h4>about us</h4>
					<div class="aboutus-right-wthree">
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
						<ul>
							<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
						</ul>
					</div>
			</div>
			<div class="col-md-4 news-letter-agileits-w3layouts">
				<h4>newsletter</h4>
				<p>signup for our weekly newsletter and get the latest updates</p>
					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter your Email" required="" />
						<input type="submit" value="Subscribe" />
					</form>
			</div>
			<div class="col-md-4 from-blog-w3-agile">
				<h4>from blog</h4>
					<div class="footer-grid1">
						<div class="footer-grid1-left">
							<a href="#" data-toggle="modal" data-target="#myModal1"><img src="<%=asset_path('blog1.jpg')%>" alt=" " class="img-responsive"></a>
							<!-- Modal1 -->
						<div class="modal fade" id="myModal1" role="dialog">
							<div class="modal-dialog">
							<!-- Modal content-->
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal">&times;</button>
										<img src="<%=asset_path('banner1.jpg')%>" alt=" " class="img-responsive">
										<h5>Eveniet ut molesti</h5>
										<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.</p>
									</div>
								</div>
							</div>
						</div>
						<!-- //Modal1 -->
						</div>
						<div class="footer-grid1-right">
							<a href="#" data-toggle="modal" data-target="#myModal1">Eveniet ut molesti</a><br>
							<span>may 21th 2016</span>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="footer-grid1">
						<div class="footer-grid1-left">
							<a href="#" data-toggle="modal" data-target="#myModal1"><img src="<%=asset_path('blog2.jpg')%>" alt=" " class="img-responsive"></a>
						</div>
						<div class="footer-grid1-right">
							<a href="#" data-toggle="modal" data-target="#myModal1">Earum rerum tenet</a><br>
							<span>june 12th 2016</span>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="footer-grid1">
						<div class="footer-grid1-left">
							<a href="#" data-toggle="modal" data-target="#myModal1"><img src="<%=asset_path('blog3.jpg')%>" alt=" " class="img-responsive"></a>
						</div>
						<div class="footer-grid1-right">
							<a href="#" data-toggle="modal" data-target="#myModal1">Maiores alias cons</a><br>
							<span>aug 20th 2016</span>
						</div>
						<div class="clearfix"> </div>
					</div>
			</div>
			<div class="clearfix"> </div>
			<div class="copy">
		        <p>© 2016 Real Plot . All Rights Reserved | Design by <a href="http://w3layouts.com/">W3layouts</a> </p>
		    </div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Construction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

<link href="//fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Real Plot Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
    function hideURLbar(){ window.scrollTo(0,1); } </script>
  </head>

  <body>
    <div class="header">
      <%= render 'layouts/header' %> 
        </div>
      <%= yield %>
  
     <%= render 'layouts/footer' %> 
  </body>
</html>